# Generated by Django 4.2.3 on 2026-05-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('proprietaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panne', models.TextField()),
                ('cout_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duree_estimee', models.DurationField(help_text='Format: HH:MM:SS')),
                ('date_reparation', models.DateField()),
                ('est_validee', models.BooleanField(default=False)),
                ('type_panne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.typepanne')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.vehicule')),
            ],
        ),
    ]
